 <script src="<?= base_url('siswa/package/src/assets/libs/jquery/dist/jquery.min.js">') ?>"></script>
 <script src="<?= base_url('siswa/package/src/assets/libs/popper.js/dist/umd/popper.min.js') ?>"></script>
 <script src="<?= base_url('siswa/package/src/assets/libs/bootstrap/dist/js/bootstrap.min.js') ?>"></script>
 <script src="<?= base_url('siswa/package/src/dist/js/app-style-switcher.js') ?>"></script>
 <script src="<?= base_url('siswa/package/src/dist/js/feather.min.js') ?>"></script>
 <script src="<?= base_url('siswa/package/src/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js') ?>"></script>
 <script src="<?= base_url('siswa/package/src/dist/js/sidebarmenu.js') ?>"></script>
 <script src="<?= base_url('siswa/package/src/dist/js/custom.min.js') ?>"></script>
 <script src="<?= base_url('siswa/package/src/assets/extra-libs/c3/d3.min.js') ?>"></script>
 <script src="<?= base_url('siswa/package/src/assets/extra-libs/c3/c3.min.js') ?>"></script>
 <script src="<?= base_url('siswa/package/src/assets/libs/chartist/dist/chartist.min.js') ?>"></script>
 <script src="<?= base_url('siswa/package/src/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js') ?>"></script>
 <script src="<?= base_url('siswa/package/src/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js') ?>/"></script>
 <script src="<?= base_url('siswa/package/src/assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js') ?>"></script>
 <script src="<?= base_url('siswa/package/src/dist/js/pages/dashboards/dashboard1.min.js') ?>"></script>